### ISSUE TITLE
Feature Request: HACS

### ISSUE THREAD

**Issue by dolenec** [frlequ/home-assistant-network-tariff#7]
Support for HACS installation (out of box).

**Comment by devdems** [comment]
@dolenec for HACS you just click on this link. You can build this link for every plugin on git by changing the owner and the repo name.

https://my.home-assistant.io/redirect/hacs_repository/?owner=frlequ&repository=home-assistant-network-tariff&category=integration

**Comment by DejanBukovec** [comment]
Hi Im try add it by HACS but link do not work. Can you make component fully compatible with HA that it can be added without editing configuration yaml? I think that this is simple task because there is no configuration needed... 
![Screenshot_20240923_171007_io homeassistant companion android (002)](https://github.com/user-attachments/assets/3f80dd68-a9a9-426b-b05d-046bf8f2aa8d)

**Comment by LeoAlioth** [comment]
Can confirm, seems like an incompatible configuration or something.

**Comment by devdems** [comment]
@DejanBukovec @LeoAlioth 

![image](https://github.com/user-attachments/assets/3ffeaf27-1be0-4528-bbc1-d5d0b718a557)

**Comment by frlequ** [comment]
Installing and updating via HACS should now work in the latest version: https://github.com/frlequ/home-assistant-network-tariff/pull/11

Use this:
[![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=frlequ&repository=home-assistant-network-tariff&category=integration)
